# Script para configurar las variables de entorno del backend
# Ejecuta este script después de obtener tus credenciales de Supabase

echo "=== Configuración del Backend - Variables de Entorno ==="
echo ""
echo "Para configurar el backend correctamente, necesitas:"
echo ""
echo "1. Copiar el archivo .env.example a .env:"
echo "   cp .env.example .env"
echo ""
echo "2. Editar el archivo .env con tus credenciales de Supabase:"
echo "   - SUPABASE_URL: La URL de tu proyecto Supabase"
echo "   - SUPABASE_SERVICE_KEY: La service key (NO la anon key)"
echo ""
echo "3. Las credenciales se encuentran en:"
echo "   Panel Supabase > Settings > API"
echo ""
echo "4. IMPORTANTE: La SERVICE_KEY es sensible y tiene privilegios de administrador"
echo "   No la compartas ni la subas a repositorios públicos"
echo ""
echo "5. Una vez configurado, puedes iniciar el servidor con:"
echo "   npm run dev"
echo ""
echo "================================================================"
